version: '2'
services:
  web:
    build: ./web
    image: simple-http
    container_name: web
    privileged: true
  client:
    build: ./client
    image: ping-curl
    container_name: client
    stdin_open: true
    tty: true
    privileged: true
    
